import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { BreadcrumbProvider } from '@/customHooks/BreadCrumbsContext'
import SideBar from '@/components/global/SideBar'
import { DashboardNav } from '@/components/global/Nav'
import localFont from 'next/font/local'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

const myCustomFont = localFont({
  src: [
    {
      path: '../assets/fonts/Fonts/OTF/Satoshi-Medium.otf',
      weight: '700',
      style: 'normal'
    },
    {
      path: '../assets/fonts/Fonts/OTF/Satoshi-Black.otf',
      weight: '900',
      style: 'black'
    },
    {
      path: '../assets/fonts/Fonts/OTF/Satoshi-Bold.otf',
      weight: '800',
      style: 'black'
    },
    {
      path: '../assets/fonts/Fonts/OTF/Satoshi-Light.otf',
      weight: '300',
      style: 'black'
    },

  ],
  variable: '--font-custom'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${myCustomFont.className}`}
      >
        <BreadcrumbProvider>
          <SideBar>
            <DashboardNav />
            <main>{children}</main>
          </SideBar>
        </BreadcrumbProvider>
      </body>
    </html>
  )
}
